export class SocialMedia {
    Android: string = '';
    Dribbble: string = '';
    Facebook: string = '';
    Flickr: string = '';
    FourSquare: string = '';
    Google: string = '';
    Instagram: string = '';
    LinkedIn: string = '';
    Pinterest: string = '';
    Reddit: string = '';
    RSS: string = '';
    Skype: string = '';
    Snapchat: string = '';
    SoundCloud: string = '';
    StumbleUpon: string = '';
    Tumblr: string = '';
    Twitter: string = '';
    Vimeo: string = '';
    Vine: string = '';
    Yahoo: string = '';
    Youtube: string = '';
}
